#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Feb 21, 2024 10:43:22 PM +07  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import beta1_support

_bgcolor = "SystemButtonFace"
_fgcolor = "SystemWindowText"
_tabfg1 = "black"
_tabfg2 = "white"
_bgmode = "light"
_tabbg1 = "#d9d9d9"
_tabbg2 = "gray40"

_style_code_ran = 0


def _style_code():
    global _style_code_ran
    if _style_code_ran:
        return
    try:
        beta1_support.root.tk.call(
            "source", os.path.join(_location, "themes", "xpnative.tcl")
        )
    except:
        pass
    style = ttk.Style()
    style.theme_use("xpnative")
    style.configure(".", font="TkDefaultFont")
    _style_code_ran = 1


class HSI:
    def __init__(self, top=None):
        """This class configures and populates the toplevel window.
        top is the toplevel containing window."""

        width = top.winfo_screenwidth()
        height = top.winfo_screenheight()
        top.geometry("1000x493+48+110")
        top.minsize(120, 1)
        top.maxsize(width, height)
        top.resizable(1, 1)
        top.title("Toplevel 0")
        top.configure(highlightcolor="SystemWindowText")

        self.top = top

        _style_code()
        self.TSizegrip1 = ttk.Sizegrip(self.top)
        self.TSizegrip1.place(anchor="se", relx=1.0, rely=1.0)

        self.Menu = ttk.Frame(self.top)
        self.Menu.place(relx=0.76, rely=0.02, relheight=0.949, relwidth=0.235)
        self.Menu.configure(relief="flat")
        self.Menu.configure(borderwidth="2")
        self.Menu.configure(relief="flat")
        
        #ปุ่มเลือกภาพ
        self.Open = ttk.Button(self.Menu)
        self.Open.place(relx=0.043, rely=0.021, height=25, width=76)
        self.Open.configure(text="""Open""")
        self.Open.configure(compound="left")
        self.Open.configure(command=beta1_support.image.import_img)
        
        # labelชื่อไฟล์
        self.filedir = ttk.Label(self.Menu)
        self.filedir.place(relx=0.374, rely=0.015, height=19, width=135)
        self.filedir.configure(font="-family {Segoe UI} -size 9")
        self.filedir.configure(relief="flat")
        self.filedir.configure(anchor="w")
        self.filedir.configure(justify="left")
        self.filedir.configure(text="""File directory""")
        self.filedir.configure(compound="left")
        # label สถานะโหลด
        self.loadstatus = ttk.Label(self.Menu)
        self.loadstatus.place(relx=0.638, rely=0.947, height=19, width=75)
        self.loadstatus.configure(font="-family {Segoe UI} -size 9")
        self.loadstatus.configure(relief="flat")
        self.loadstatus.configure(anchor="w")
        self.loadstatus.configure(justify="left")
        self.loadstatus.configure(text="""Load status""")
        self.loadstatus.configure(compound="left")

        # แสดงสี2
        self.HUE2pre = ttk.Frame(self.Menu)
        self.HUE2pre.place(relx=0.511, rely=0.59, relheight=0.346, relwidth=0.447)
        self.HUE2pre.configure(relief="groove")
        self.HUE2pre.configure(borderwidth="2")
        self.HUE2pre.configure(relief="groove")

        # แสดงสี1
        self.HUE1pre = ttk.Frame(self.Menu)
        self.HUE1pre.place(relx=0.043, rely=0.59, relheight=0.346, relwidth=0.447)
        self.HUE1pre.configure(relief="groove")
        self.HUE1pre.configure(borderwidth="2")
        self.HUE1pre.configure(relief="groove")

        self.loadbar = ttk.Progressbar(self.Menu)
        self.loadbar.place(
            relx=0.043, rely=0.947, relwidth=0.511, relheight=0.0, height=18
        )
        self.loadbar.configure(length="120")

        # tab
        self.TNotebook1 = ttk.Notebook(self.Menu)
        self.TNotebook1.place(relx=0.043, rely=0.085, relheight=0.483, relwidth=0.911)
        self.TNotebook1.configure(takefocus="")
        # tab1
        self.TNotebook1_t1 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t1, padding=3)
        self.TNotebook1.tab(
            0,
            text="""start""",
            compound="left",
            underline="""-1""",
        )
        self.TNotebook1_t1.configure(highlightcolor="SystemWindowText")
        # tab2
        self.TNotebook1_t2 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t2, padding=3)
        self.TNotebook1.tab(
            1,
            text="""end""",
            compound="left",
            underline="""-1""",
        )
        self.TNotebook1_t2.configure(highlightcolor="SystemWindowText")
# =============================================================================================================================
        # HUE1
        self.HUE_label1 = ttk.Label(self.TNotebook1_t1)
        self.HUE_label1.place(relx=0.048, rely=0.05, height=19, width=35)
        self.HUE_label1.configure(font="TkDefaultFont")
        self.HUE_label1.configure(relief="flat")
        self.HUE_label1.configure(anchor="w")
        self.HUE_label1.configure(justify="left")
        self.HUE_label1.configure(text="""HUE""")
        self.HUE_label1.configure(compound="left")

        self.HUE_scale1 = ttk.Scale(self.TNotebook1_t1, from_=0, to=360.0)
        self.HUE_scale1.place(relx=0.048, rely=0.15, relheight=0.12, relwidth=0.619)
        self.HUE_scale1.configure(length="130")
        self.HUE_scale1.configure(takefocus="")
        self.HUE_scale1.configure(command=beta1_support.st_lentoval)

        self.HUE_entry1 = ttk.Entry(self.TNotebook1_t1)
        self.HUE_entry1.place(relx=0.714, rely=0.15, relheight=0.115, relwidth=0.219)
        self.HUE_entry1.configure(takefocus="")
        self.HUE_entry1.configure(cursor="ibeam")
#================================================================================================================================
        # intensity1
        self.Intense_label1 = ttk.Label(self.TNotebook1_t1)
        self.Intense_label1.place(relx=0.048, rely=0.3, height=19, width=65)
        self.Intense_label1.configure(font="TkDefaultFont")
        self.Intense_label1.configure(relief="flat")
        self.Intense_label1.configure(anchor="w")
        self.Intense_label1.configure(justify="left")
        self.Intense_label1.configure(text="""Intensity""")
        self.Intense_label1.configure(compound="left")

        self.Intensity_scale1 = ttk.Scale(self.TNotebook1_t1, from_=0, to=255.0)
        self.Intensity_scale1.place(
            relx=0.048, rely=0.45, relheight=0.12, relwidth=0.619
        )
        self.Intensity_scale1.configure(length="130")
        self.Intensity_scale1.configure(takefocus="")
        self.Intensity_scale1.configure(command=beta1_support.inten_lentoval)

        self.Intensity_Entry1 = ttk.Entry(self.TNotebook1_t1)
        self.Intensity_Entry1.place(
            relx=0.714, rely=0.45, relheight=0.115, relwidth=0.219
        )
        self.Intensity_Entry1.configure(takefocus="")
        self.Intensity_Entry1.configure(cursor="ibeam")

# =================================================================================================================================
        # satuation1
        self.Satuation_label1 = ttk.Label(self.TNotebook1_t1)
        self.Satuation_label1.place(relx=0.048, rely=0.6, height=19, width=55)
        self.Satuation_label1.configure(font="TkDefaultFont")
        self.Satuation_label1.configure(relief="flat")
        self.Satuation_label1.configure(anchor="w")
        self.Satuation_label1.configure(justify="left")
        self.Satuation_label1.configure(text="""Satuation""")
        self.Satuation_label1.configure(compound="left")

        self.Satuation_scale1 = ttk.Scale(self.TNotebook1_t1, from_=0, to=1.0)
        self.Satuation_scale1.place(
            relx=0.048, rely=0.75, relheight=0.12, relwidth=0.619
        )
        self.Satuation_scale1.configure(length="130")
        self.Satuation_scale1.configure(takefocus="")
        self.Satuation_scale1.configure(command=beta1_support.sat_lentoval)

        self.Satuation_entry1 = ttk.Entry(self.TNotebook1_t1)
        self.Satuation_entry1.place(
            relx=0.714, rely=0.75, relheight=0.115, relwidth=0.219
        )
        self.Satuation_entry1.configure(takefocus="")
        self.Satuation_entry1.configure(cursor="ibeam")

# =============================================================================================================================
        # HUE2
        self.HUE_label2 = ttk.Label(self.TNotebook1_t2)
        self.HUE_label2.place(relx=0.048, rely=0.05, height=19, width=35)
        self.HUE_label2.configure(font="-family {Segoe UI} -size 9")
        self.HUE_label2.configure(relief="flat")
        self.HUE_label2.configure(anchor="w")
        self.HUE_label2.configure(justify="left")
        self.HUE_label2.configure(text="""HUE""")
        self.HUE_label2.configure(compound="left")

        self.HUE_entry2 = ttk.Entry(self.TNotebook1_t2)
        self.HUE_entry2.place(relx=0.714, rely=0.15, relheight=0.115, relwidth=0.219)
        self.HUE_entry2.configure(font="-family {Segoe UI} -size 9")
        self.HUE_entry2.configure(cursor="ibeam")

        self.HUE_scale2 = ttk.Scale(self.TNotebook1_t2, from_=0, to=360.0)
        self.HUE_scale2.place(relx=0.048, rely=0.15, relheight=0.12, relwidth=0.619)
        self.HUE_scale2.configure(length="130")
        self.HUE_scale2.configure(command=beta1_support.ed_lentoval)

# =============================================================================================================================
        # Intensity2
        self.Intense_label2 = ttk.Label(self.TNotebook1_t2)
        self.Intense_label2.place(relx=0.048, rely=0.3, height=19, width=65)
        self.Intense_label2.configure(font="-family {Segoe UI} -size 9")
        self.Intense_label2.configure(relief="flat")
        self.Intense_label2.configure(anchor="w")
        self.Intense_label2.configure(justify="left")
        self.Intense_label2.configure(text="""Intensity""")
        self.Intense_label2.configure(compound="left")

        self.Intensity_scale2 = ttk.Scale(self.TNotebook1_t2, from_=0, to=255.0)
        self.Intensity_scale2.place(
            relx=0.048, rely=0.45, relheight=0.12, relwidth=0.619
        )
        self.Intensity_scale2.configure(length="130")
        self.Intensity_scale2.configure(command=beta1_support.inten2_lentoval)

        self.Intensity_Entry2 = ttk.Entry(self.TNotebook1_t2)
        self.Intensity_Entry2.place(
            relx=0.714, rely=0.45, relheight=0.115, relwidth=0.219
        )
        self.Intensity_Entry2.configure(font="-family {Segoe UI} -size 9")
        self.Intensity_Entry2.configure(cursor="ibeam")
        

# =============================================================================================================================
        # Satuation2
        self.Satuation_label2 = ttk.Label(self.TNotebook1_t2)
        self.Satuation_label2.place(relx=0.048, rely=0.6, height=19, width=55)
        self.Satuation_label2.configure(font="-family {Segoe UI} -size 9")
        self.Satuation_label2.configure(relief="flat")
        self.Satuation_label2.configure(anchor="w")
        self.Satuation_label2.configure(justify="left")
        self.Satuation_label2.configure(text="""Satuation""")
        self.Satuation_label2.configure(compound="left")

        self.Satuation_entry2 = ttk.Entry(self.TNotebook1_t2)
        self.Satuation_entry2.place(
            relx=0.714, rely=0.75, relheight=0.115, relwidth=0.219
        )
        self.Satuation_entry2.configure(font="-family {Segoe UI} -size 9")
        self.Satuation_entry2.configure(cursor="ibeam")

        self.Satuation_scale2 = ttk.Scale(self.TNotebook1_t2, from_=0, to=1.0)
        self.Satuation_scale2.place(
            relx=0.048, rely=0.75, relheight=0.12, relwidth=0.619
        )
        self.Satuation_scale2.configure(length="130")
        self.Satuation_scale2.configure(command=beta1_support.sat2_lentoval)

# =============================================================================================================================


        self.TFrame1 = ttk.Frame(self.top)
        self.TFrame1.place(relx=0.01, rely=0.02, relheight=0.949, relwidth=0.745)

        self.TFrame1.configure(relief="groove")
        self.TFrame1.configure(borderwidth="2")
        self.TFrame1.configure(relief="groove")


def start_up():
    beta1_support.main()


if __name__ == "__main__":
    beta1_support.main()
